# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'otp_component' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    team = ENV['APPLE_DEVELOPMENT_TEAM']
    if team.nil? || team.empty?
      signing_local = File.expand_path('Signing.local.xcconfig', __dir__)
      if File.exist?(signing_local)
        team = File.read(signing_local)[/DEVELOPMENT_TEAM\s*=\s*(\S+)/, 1]
      end
    end

    if team && !team.empty?
      require 'xcodeproj'
      app_project_path = File.join(__dir__, 'otp_component.xcodeproj')
      [installer.pods_project, Xcodeproj::Project.open(app_project_path)].each do |project|
        project.targets.each do |target|
          target.build_configurations.each do |build_config|
            build_config.build_settings['DEVELOPMENT_TEAM'] = team
            build_config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
          end
        end
        project.save
      end
    end
  end
end
